# Generated by Django 3.1.2 on 2020-10-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('colour', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('door', models.PositiveSmallIntegerField(max_length=1)),
                ('features', models.TextField()),
                ('transmission', models.CharField(choices=[(None, 'Choose'), ('a', 'Automatic'), ('m', 'Manual')], max_length=1)),
                ('fuel', models.CharField(choices=[(None, 'Choose'), ('p', 'Petrol'), ('d', 'Diesel')], max_length=1)),
                ('interior', models.CharField(choices=[(None, 'Choose'), ('l', 'Leather'), ('f', 'Fabric')], max_length=1)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
