# Generated by Django 3.1.2 on 2020-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201024_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='door',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
