# Generated by Django 3.1.2 on 2020-10-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201024_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='maker',
            field=models.CharField(default='honda', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.car')),
            ],
        ),
    ]
