# Generated by Django 3.1.2 on 2020-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[(None, 'Choose'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior',
            field=models.CharField(choices=[(None, 'Choose'), ('Leather', 'Leather'), ('Fabric', 'Fabric')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[(None, 'Choose'), ('Automatic', 'Automatic'), ('Manual', 'Z')], max_length=10),
        ),
    ]
