# Generated by Django 3.1.2 on 2020-10-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20201025_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mainpic',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic5',
        ),
    ]
