# Generated by Django 3.1.2 on 2020-10-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20201025_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mainpic',
            field=models.ImageField(default='dff', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='pic1',
            field=models.ImageField(default='dsf', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='pic2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic4',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic5',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
