# Generated by Django 3.1.2 on 2020-10-29 20:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20201028_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mainpic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='images'),
        ),
    ]
