# Generated by Django 3.1.2 on 2020-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20201029_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='features',
            new_name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='extra_features',
            field=models.CharField(default='dhfhf', max_length=500),
            preserve_default=False,
        ),
    ]
