# Generated by Django 3.1.2 on 2020-10-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20201030_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='extra_features',
            field=models.TextField(max_length=500),
        ),
    ]
