# Generated by Django 3.1.2 on 2020-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20201030_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='foreign_or_naija_used',
            field=models.CharField(choices=[(None, 'Choose'), ('Foreign Used', 'Foreign Used'), ('Naija Used', 'Naija Used')], default='kdjfkfkf', max_length=12),
            preserve_default=False,
        ),
    ]
