# Generated by Django 3.1.2 on 2020-11-03 11:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_car_foreign_or_naija_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[600, 400], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pic2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[600, 400], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pic3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[600, 400], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pic4',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[600, 400], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pic5',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[600, 400], upload_to='images'),
        ),
    ]
